# docker-compose.ci.yml
version: '3.7'

services:
  my-laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -"80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=testing
      - DB_HOST=mysql
      - DB_DATABASE=ems_testing
      - DB_USERNAME=ems_testing
      - DB_PASSWORD=${DB_PASSWORD}
      - WWWGROUP=${WWWGROUP}
      - WWWUSER=${WWWUSER}
    depends_on:
      - mysql-test
    networks:
      - sail

  mysql-test:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ems_testing
      MYSQL_USER: ems_testing
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - sail
    healthcheck:
      # ...
    volumes:
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
networks:
  sail:
    driver: bridge