# docker-compose.ci.yml
version: '3.7'

services:
  my-laravel-app:
    build: .
    depends_on:
      - mysql-test
    networks:
      - sail
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ems_testing
      # ...その他の設定
    networks:
      - sail
    healthcheck:
      # ...
    volumes:
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
networks:
  sail:
    driver: bridge