services:
    my-laravel-app:
        container_name: EMS
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        command: "sh -c \" \
            id -u sail || useradd -m sail && \
            chown -R www-data:www-data /var/www/html/storage && \
            chmod -R 777 /var/www/html/storage && \
            chown -R www-data:www-data /var/www/html/public && \
            chmod -R 777 /var/www/html/public && \
            rm -rf /var/www/html/public/storage && \
            ln -s /var/www/html/storage/app/public /var/www/html/public/storage && \
            apache2-foreground \"\n"
        networks:
            - sail
        depends_on:
            - mysql
            - mysql-test
    mysql:
        container_name: mysql
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql-test:/var/lib/mysql'
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mysql-test:
        container_name: mysql-test
        image: 'mysql:8.0'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password123
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ems_testing
            MYSQL_USER: ems_testing
            MYSQL_PASSWORD: password123
        volumes:
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-ppassword123'
            retries: 3
            timeout: 5s
    phpMyAdmin:
        container_name: phpMyAdmin
        image: phpmyadmin/phpmyadmin
        links:
            - 'mysql:mysql'
        ports:
            - '8080:80'
        environment:
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            PMA_HOST: mysql
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-mysql-test:
    driver: 
