name: Deploy EventBridge Rule

on:
  workflow_dispatch:  # 手動実行用（必要なら schedule や push にも対応可）

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy-eventbridge:
    name: Deploy EventBridge Rule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Prepare CloudFormation template for EventBridge
        run: |
          sed "s|__CLUSTER_ARN__|${{ secrets.ECS_CLUSTER_ARN }}|g" cloudformation/eventbridge.template.yml \
          | sed "s|__ROLE_ARN__|${{ secrets.EXEC_ROLE_ARN }}|g" \
          | sed "s|__TASK_DEF_ARN__|${{ secrets.TASK_DEF_ARN }}|g" \
          | sed "s|__SUBNET_ID__|${{ secrets.SUBNET_ID }}|g" \
          | sed "s|__SECURITY_GROUP_ID__|${{ secrets.SECURITY_GROUP_ID }}|g" \
          > cloudformation/eventbridge.yml

      - name: Deploy EventBridge rule via CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/eventbridge.yml \
            --stack-name eventbridge-rule-stack \
            --capabilities CAPABILITY_NAMED_IAM
