name: EMS CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:   
          file: ./docker-compose.yml  # ここにファイル名を指定
          version: latest
      
      - name: Install dockerize
        run: |
          wget -qO- https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar xvz -C /usr/local/bin
          dockerize --version

      - name: Copy .env.testing to .env
        run: cp .env.testing .env

      - name: Set up environment variables
        run: |
          echo "WWWGROUP=www-data" >> .env
          echo "WWWUSER=www-data" >> .env

      - name: Build and start services
        run: docker compose up -d

      # MySQLコンテナが立ち上がるまで待つ
      - name: Wait for MySQL to be ready
        run: dockerize -wait tcp://mysql-test:3306 -timeout 5m
      
      - name: Wait for Laravel App to be ready
        run: dockerize -wait http://my-laravel-app:80 -timeout 5m

      - name: Inspect services
        run: docker compose ps

      - name: Inspect Docker network
        run: docker network ls

      - name: Test MySQL connection
        run: docker compose exec EMS ping -c 4 mysql-test

      - name: Check MySQL status
        run: docker compose exec mysql-test mysqladmin ping -ppassword123

      - name: Inspect Docker bridge network details
        run: docker network inspect bridge

      - name: Inspect Docker bridge network ems_sail details
        run: docker network inspect ems_sail

      - name: Test MySQL connection
        run: docker compose exec my-laravel-app ping -c 4 mysql-test

      # 最新の依存関係を反映
      - name: Install dependencies
        run: docker compose exec my-laravel-app composer install --prefer-dist --no-progress --no-suggest

      - name: Generate application key
        run: docker compose exec my-laravel-app php artisan key:generate

      - name: Run migrations
        run: docker compose exec my-laravel-app php artisan migrate

      - name: Run feature tests via PHPUnit
        run: docker compose exec my-laravel-app php artisan test

      - name: Stop and remove containers
        run: docker compose down

      # - name: Run Laravel Sail tests
      #   run: ./vendor/bin/phpunit